repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4
    hooks:
    -    id: autopep8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -    id: trailing-whitespace
    -    id: end-of-file-fixer
    -    id: flake8
    -    id: requirements-txt-fixer
