language: python
python:
  - "nightly"
  - "3.7-dev" # 3.7 development branch
  - "3.6-dev" # 3.6 development branch
  - "3.6"
  - "3.5-dev" # 3.5 development branch
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
# command to run tests
script:
  - python -m unittest discover
  - python bank2ynab.py
  - pip install flake8
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] && [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then flake8 --builtins=unicode; fi
  - pip install codecov
  - pip install coverage
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]] && [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then coverage run bank2ynab.py; fi
after_success:
  - codecov 
  - coverage report
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/23be690947c65bd7a84b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
